general {
    # Command run when loginctl lock-session is invoked
    lock_cmd = pidof hyprlock || hyprlock

    # Lock before system goes to sleep
    before_sleep_cmd = loginctl lock-session

    # Prevent keypresses needed to wake display from re-triggering DPMS on some setups
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Dim screen (2.5 mins / 150s)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Lock screen (5 mins / 300s)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off display (5.5 mins / 330s)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend system (30 mins / 1800s)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
